export type UtilityType =
  | 'smoke-block'
  | 'wall-place'
  | 'flash'
  | 'recon'
  | 'heal'
  | 'concuss'
  | 'stun'
  | 'suppress'
  | 'decay'
  | 'slow'
  | 'postplant'
  | 'entry'
  | 'mobility'
  | 'lurk'
  | 'anchor'
  | 'area-denial'
  | 'crowd-control'
  | 'info'
  | 'shield'
  | 'revive'
  | 'trap'
  | 'tp'
  | 'stim'
  | 'wall';

export type CompositionArchetype =
  | 'double-controller'
  | 'double-duelist'
  | 'double-initiator'
  | 'double-sentinel'
  | 'standard-balanced'
  | 'aggressive-tempo'
  | 'slow-control'
  | 'pincer';

export type ActiveMapName = 'Ascent' | 'Bind' | 'Breeze' | 'Fracture' | 'Haven' | 'Icebox' | 'Lotus' | 'Pearl' | 'Split' | 'Sunset' | 'Abyss' | 'Corrode';

export interface MapRating {
  map: ActiveMapName;
  score: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;
  notes: string;
}

export interface FullAgentProfile {
  name: string;
  role: 'Duelista' | 'Controlador' | 'Iniciador' | 'Centinela';
  utility: UtilityType[];
  primaryUtility: UtilityType;
  difficulty: 1 | 2 | 3 | 4 | 5;
  mapRatings: MapRating[];
  bestWith: string[];
  strongAgainst: string[];
  weakAgainst: string[];
  directReplacements: string[];
  archetypes: CompositionArchetype[];
  description: string;
  playstyle: string;
  proPickRate: number;
  proWinRate: number;
}

export const ALL_AGENTS: FullAgentProfile[] = [
  {
    name: 'Miks',
    role: 'Controlador',
    utility: ['smoke-block', 'heal', 'concuss', 'crowd-control', 'area-denial'],
    primaryUtility: 'smoke-block',
    difficulty: 3,
    mapRatings: [
      { map: 'Ascent', score: 6, notes: 'Funciona pero Omen/Astra son mejores para split control' },
      { map: 'Bind', score: 8, notes: 'Multi-smoke + stim enablea executes rápidos por dos frentes' },
      { map: 'Breeze', score: 3, notes: 'Sin wall-control, sufre en líneas largas abiertas' },
      { map: 'Fracture', score: 8, notes: 'Pincer + Harmonize para entries coordinados' },
      { map: 'Haven', score: 6, notes: 'Aceptable en 3-sites para rotates rápidos' },
      { map: 'Icebox', score: 3, notes: 'Falta wall-control vertical, mejor Viper' },
      { map: 'Lotus', score: 5, notes: 'Util pero inferior a Omen/Viper en control de puertas' },
      { map: 'Pearl', score: 5, notes: 'Mediocre, Astra/Omen tienen mejor control global' },
      { map: 'Split', score: 8, notes: 'Multi-smoke ideal para chokes cerrados + Harmonize para Raze' },
      { map: 'Sunset', score: 6, notes: 'Aceptable, Clove/Omen tienen más presencia' },
      { map: 'Abyss', score: 7, notes: 'Bassquake knockback puede enviar al vacío' },
      { map: 'Corrode', score: 4, notes: 'Falta wall-control, Viper/Harbor mejores' },
    ],
    bestWith: ['Neon', 'Raze', 'Jett', 'Tejo', 'Breach', 'Gekko'],
    strongAgainst: ['Cypher', 'Killjoy', 'Sage'],
    weakAgainst: ['Viper', 'Harbor', 'KAY/O'],
    directReplacements: ['Omen', 'Clove', 'Brimstone', 'Astra'],
    archetypes: ['aggressive-tempo', 'double-controller'],
    description: 'Controlador de soporte basado en sonido con smokes, curación y crowd-control.',
    playstyle: 'Agresivo-cercano: juega cerca de los duelistas para dar Harmonize y apoyar entradas.',
    proPickRate: 6.2,
    proWinRate: 48.3,
  },
  {
    name: 'Omen',
    role: 'Controlador',
    utility: ['smoke-block', 'flash', 'tp', 'lurk'],
    primaryUtility: 'smoke-block',
    difficulty: 3,
    mapRatings: [
      { map: 'Ascent', score: 9, notes: 'Top-tier: smokes reactivas + paranoia para mid-control' },
      { map: 'Bind', score: 7, notes: 'Bueno pero Brimstone/Astra tienen smokes más rápidas para executes' },
      { map: 'Breeze', score: 5, notes: 'Falta wall, Viper es reina aquí' },
      { map: 'Fracture', score: 8, notes: 'TP + paranoia para rotaciones en pincer' },
      { map: 'Haven', score: 9, notes: 'Excelente en 3-sites, TP para rotates' },
      { map: 'Icebox', score: 6, notes: 'Aceptable, pero Viper es necesaria para vertical' },
      { map: 'Lotus', score: 8, notes: 'TP para rotar por puertas, paranoia para executes' },
      { map: 'Pearl', score: 8, notes: 'Smokes reactivas + TP para control de mid' },
      { map: 'Split', score: 8, notes: 'TP + smokes para control de alturas' },
      { map: 'Sunset', score: 9, notes: 'Top-tier en mapa compacto, paranoia en Elbow' },
      { map: 'Abyss', score: 7, notes: 'Bueno, TP para rotar entre platforms' },
      { map: 'Corrode', score: 7, notes: 'TP + paranoia para control de chokes' },
    ],
    bestWith: ['Sova', 'Fade', 'Raze', 'Jett', 'Viper', 'Harbor'],
    strongAgainst: ['Cypher', 'Sage', 'Killjoy'],
    weakAgainst: ['KAY/O', 'Skye', 'Breach'],
    directReplacements: ['Miks', 'Clove', 'Brimstone', 'Astra'],
    archetypes: ['standard-balanced', 'double-controller', 'slow-control'],
    description: 'Controlador flexible con humos recargables y capacidad de lurk.',
    playstyle: 'Flexible: puede jugar atrás dando smokes o flanquear con TP. Paranoia habilita entries.',
    proPickRate: 14.5,
    proWinRate: 49.8,
  },
  {
    name: 'Brimstone',
    role: 'Controlador',
    utility: ['smoke-block', 'area-denial', 'postplant', 'stim'],
    primaryUtility: 'smoke-block',
    difficulty: 2,
    mapRatings: [
      { map: 'Ascent', score: 7, notes: 'Smokes instantáneas buenas para split A/B' },
      { map: 'Bind', score: 9, notes: 'Excelente: smokes rápidas + molly para post-plant en executes por dos frentes' },
      { map: 'Breeze', score: 3, notes: 'Smokes sin wall no cortan líneas largas' },
      { map: 'Fracture', score: 9, notes: 'Top-tier: Stim + smokes rápidas para pincers' },
      { map: 'Haven', score: 7, notes: 'Stim para rotates rápidos entre 3 sites' },
      { map: 'Icebox', score: 4, notes: 'Viper/Harbor mejores para verticalidad' },
      { map: 'Lotus', score: 5, notes: 'Acceptable pero falta flexibilidad de Omen/Astra' },
      { map: 'Pearl', score: 6, notes: 'Smokes sólidas pero Astra tiene mejor rango' },
      { map: 'Split', score: 8, notes: 'Stim + molly ideales para chokes cerrados' },
      { map: 'Sunset', score: 8, notes: 'Bueno en mapa compacto, stim para mid-control' },
      { map: 'Abyss', score: 5, notes: 'Aceptable pero falta movilidad de otros' },
      { map: 'Corrode', score: 5, notes: 'Sin wall, inferior a Viper/Harbor' },
    ],
    bestWith: ['Raze', 'Breach', 'Neon', 'Gekko', 'Viper'],
    strongAgainst: ['Killjoy', 'Cypher', 'Sage'],
    weakAgainst: ['KAY/O', 'Sova'],
    directReplacements: ['Omen', 'Astra', 'Clove', 'Miks'],
    archetypes: ['aggressive-tempo', 'double-controller'],
    description: 'Controlador de executes rápidos con smokes instantáneas y post-plant con molly.',
    playstyle: 'Execute-oriented: usa Stim + smokes para entradas rápidas y molly para post-plant.',
    proPickRate: 8.2,
    proWinRate: 50.5,
  },
  {
    name: 'Viper',
    role: 'Controlador',
    utility: ['wall-place', 'area-denial', 'decay', 'postplant', 'anchor'],
    primaryUtility: 'wall-place',
    difficulty: 4,
    mapRatings: [
      { map: 'Ascent', score: 7, notes: 'Buen complemento con Omen, wall para mid-control' },
      { map: 'Bind', score: 8, notes: 'Wall + molly ideales para executes A/B' },
      { map: 'Breeze', score: 10, notes: 'Reina indiscutible: wall corta todo el mapa' },
      { map: 'Fracture', score: 8, notes: 'Wall para pincers, molly para post-plant' },
      { map: 'Haven', score: 7, notes: 'Wall para cortar un site entero en 3-sites' },
      { map: 'Icebox', score: 10, notes: 'Esencial: wall para control vertical, molly para Belt' },
      { map: 'Lotus', score: 8, notes: 'Doble controller ideal con Omen/Clove' },
      { map: 'Pearl', score: 6, notes: 'Buena pero Astra/Omen tienen más presencia' },
      { map: 'Split', score: 9, notes: 'Excelente: wall para Heaven/Screens control' },
      { map: 'Sunset', score: 6, notes: 'Aceptable pero Omen es más versátil' },
      { map: 'Abyss', score: 8, notes: 'Wall para controlar vacío + molly para post-plant' },
      { map: 'Corrode', score: 9, notes: 'Wall para cortar líneas penetrables, combo con Harbor' },
    ],
    bestWith: ['Omen', 'Brimstone', 'Harbor', 'Sova', 'Killjoy', 'Cypher'],
    strongAgainst: ['Sage', 'Cypher', 'Deadlock'],
    weakAgainst: ['KAY/O', 'Sova', 'Tejo'],
    directReplacements: ['Harbor'],
    archetypes: ['double-controller', 'slow-control'],
    description: 'Controladora de pared persistente con control de mapa y post-plant.',
    playstyle: 'Planificación previa: colocar wall al inicio, managear combustible para rondas largas.',
    proPickRate: 18.3,
    proWinRate: 51.2,
  },
  {
    name: 'Astra',
    role: 'Controlador',
    utility: ['smoke-block', 'stun', 'concuss', 'crowd-control', 'postplant'],
    primaryUtility: 'smoke-block',
    difficulty: 5,
    mapRatings: [
      { map: 'Ascent', score: 8, notes: 'Control global + stun para split executes' },
      { map: 'Bind', score: 7, notes: 'Buena pero Brimstone más rápido para executes' },
      { map: 'Breeze', score: 5, notes: 'Falta wall, Viper superior' },
      { map: 'Fracture', score: 7, notes: 'Utilidad global para pincers' },
      { map: 'Haven', score: 9, notes: 'Excelente en 3-sites: estrellas cubren todo el mapa' },
      { map: 'Icebox', score: 6, notes: 'Falta wall vertical, pero útil para control' },
      { map: 'Lotus', score: 8, notes: 'Control global ideal para mapa 3-sites' },
      { map: 'Pearl', score: 9, notes: 'Excelente: presencia global en mapa de rotaciones largas' },
      { map: 'Split', score: 7, notes: 'Buena pero Viper tiene wall para alturas' },
      { map: 'Sunset', score: 8, notes: 'Control global útil en mapa compacto' },
      { map: 'Abyss', score: 8, notes: 'Gravity well + stun para enviar al vacío' },
      { map: 'Corrode', score: 7, notes: 'Control global para conectar sitios' },
    ],
    bestWith: ['Jett', 'Raze', 'Sova', 'Viper', 'Killjoy'],
    strongAgainst: ['Sage', 'Cypher', 'Deadlock'],
    weakAgainst: ['KAY/O', 'Breach'],
    directReplacements: ['Omen', 'Clove', 'Brimstone', 'Miks'],
    archetypes: ['double-controller', 'slow-control'],
    description: 'Controladora con presencia global y utilidad versátil (smoke, stun, pull).',
    playstyle: 'Global: colocar estrellas estratégicamente, usar utilidad reactiva desde cualquier lugar.',
    proPickRate: 10.1,
    proWinRate: 50.2,
  },
  {
    name: 'Clove',
    role: 'Controlador',
    utility: ['smoke-block', 'decay', 'heal', 'revive'],
    primaryUtility: 'smoke-block',
    difficulty: 2,
    mapRatings: [
      { map: 'Ascent', score: 6, notes: 'Aceptable pero Omen/Astra tienen más presencia' },
      { map: 'Bind', score: 7, notes: 'Smokes post-muerte + heal para executes agresivos' },
      { map: 'Breeze', score: 4, notes: 'Falta wall, Viper es necesaria' },
      { map: 'Fracture', score: 7, notes: 'Self-rez permite plays agresivos en pincer' },
      { map: 'Haven', score: 7, notes: 'Heal + smokes para rotates entre sites' },
      { map: 'Icebox', score: 5, notes: 'Falta wall vertical para control de alturas' },
      { map: 'Lotus', score: 6, notes: 'Aceptable pero inferior a Omen/Astra' },
      { map: 'Pearl', score: 6, notes: 'Buena opción si tu equipo necesita heal adicional' },
      { map: 'Split', score: 7, notes: 'Smokes post-muerte útiles en chokes cerrados' },
      { map: 'Sunset', score: 8, notes: 'Sólida en mapa compacto, Ruse revive + decay' },
      { map: 'Abyss', score: 7, notes: 'Decay para control de vacío' },
      { map: 'Corrode', score: 6, notes: 'Falta wall pero healing es útil' },
    ],
    bestWith: ['Jett', 'Neon', 'Raze', 'Phoenix', 'Yoru'],
    strongAgainst: ['Sage', 'Deadlock'],
    weakAgainst: ['KAY/O', 'Sova', 'Breach'],
    directReplacements: ['Omen', 'Brimstone', 'Astra', 'Miks'],
    archetypes: ['aggressive-tempo', 'standard-balanced'],
    description: 'Controladora agresiva con utilidad post-muerte y self-revive.',
    playstyle: 'Agresiva: jugar más cerca de duelistas, Ruse revive para plays audaces.',
    proPickRate: 5.8,
    proWinRate: 52.2,
  },
  {
    name: 'Harbor',
    role: 'Controlador',
    utility: ['wall-place', 'area-denial', 'crowd-control'],
    primaryUtility: 'wall-place',
    difficulty: 4,
    mapRatings: [
      { map: 'Ascent', score: 5, notes: 'Bueno pero menos versátil que Omen/Astra' },
      { map: 'Bind', score: 6, notes: 'Cascade + High Tide para executes' },
      { map: 'Breeze', score: 9, notes: 'Excelente: High Tide + wall para cortar líneas largas' },
      { map: 'Fracture', score: 7, notes: 'Walls móviles para pincers coordinados' },
      { map: 'Haven', score: 6, notes: 'Walls para cortar rotaciones entre sites' },
      { map: 'Icebox', score: 8, notes: 'Buen complemento para Viper, wall para verticalidad' },
      { map: 'Lotus', score: 7, notes: 'Cascade + High Tide para control de puertas' },
      { map: 'Pearl', score: 5, notes: 'Inferior a otros controladores en este mapa' },
      { map: 'Split', score: 6, notes: 'Walls para control de alturas pero Viper mejor' },
      { map: 'Sunset', score: 5, notes: 'Aceptable pero Omen/Clove más efectivos' },
      { map: 'Abyss', score: 8, notes: 'Walls móviles para control de plataformas' },
      { map: 'Corrode', score: 9, notes: 'Excelente: High Tide para conectar sitios' },
    ],
    bestWith: ['Omen', 'Viper', 'Miks', 'Jett', 'Raze', 'Sova'],
    strongAgainst: ['Cypher', 'Sage', 'Deadlock'],
    weakAgainst: ['KAY/O', 'Tejo'],
    directReplacements: ['Viper'],
    archetypes: ['double-controller', 'slow-control'],
    description: 'Controlador de paredes móviles para executes y control de geometría.',
    playstyle: 'Ejecución móvil: usar Cascade/High Tide para avanzar detrás de pared y tomar espacio.',
    proPickRate: 4.5,
    proWinRate: 49.5,
  },
  {
    name: 'Jett',
    role: 'Duelista',
    utility: ['entry', 'mobility', 'lurk'],
    primaryUtility: 'entry',
    difficulty: 4,
    mapRatings: [
      { map: 'Ascent', score: 9, notes: 'Classic: dash + Operator para mid-control' },
      { map: 'Bind', score: 8, notes: 'Dash para entries rápidas en chokes' },
      { map: 'Breeze', score: 9, notes: 'Operator + dash en líneas largas' },
      { map: 'Fracture', score: 7, notes: 'Buena pero Raze/Neon más efectivos en pincer' },
      { map: 'Haven', score: 8, notes: 'Dash + updraft para control de 3-sites' },
      { map: 'Icebox', score: 9, notes: 'Top-tier: updraft para ángulos elevados' },
      { map: 'Lotus', score: 8, notes: 'Dash para executar en 3-sites' },
      { map: 'Pearl', score: 9, notes: 'Operator + dash para mid-control' },
      { map: 'Split', score: 7, notes: 'Buena pero Raze tiene más explosividad en chokes' },
      { map: 'Sunset', score: 8, notes: 'Dash + updraft para mapa compacto' },
      { map: 'Abyss', score: 9, notes: 'Operator king en mapa sin bordes' },
      { map: 'Corrode', score: 8, notes: 'Dash para entries rápidas en chokes' },
    ],
    bestWith: ['Sova', 'Omen', 'KAY/O', 'Skye', 'Viper'],
    strongAgainst: ['Sage', 'Cypher', 'Chamber'],
    weakAgainst: ['Raze', 'Tejo', 'Breach'],
    directReplacements: ['Raze', 'Neon', 'Yoru', 'Waylay'],
    archetypes: ['standard-balanced', 'aggressive-tempo'],
    description: 'Duelista de entry con movilidad aérea y capacidad de Operator.',
    playstyle: 'Entry/Operator: dash para tomar espacio, updraft para ángulos, Operator en líneas largas.',
    proPickRate: 22.0,
    proWinRate: 48.5,
  },
  {
    name: 'Raze',
    role: 'Duelista',
    utility: ['entry', 'area-denial', 'mobility'],
    primaryUtility: 'entry',
    difficulty: 3,
    mapRatings: [
      { map: 'Ascent', score: 8, notes: 'Satchel + Boombot para limpiar corners' },
      { map: 'Bind', score: 9, notes: 'Excelente: satchel + nade para chokes cerrados' },
      { map: 'Breeze', score: 7, notes: 'Buena pero Jett mejor para líneas largas' },
      { map: 'Fracture', score: 10, notes: 'Reina: satchel + nade para pincers coordinados' },
      { map: 'Haven', score: 8, notes: 'Satchel para rotates rápidos entre 3-sites' },
      { map: 'Icebox', score: 8, notes: 'Satchel para verticalidad + nade para Belt' },
      { map: 'Lotus', score: 9, notes: 'Excelente: satchel para puertas + nade para corners' },
      { map: 'Pearl', score: 7, notes: 'Buena pero Jett tiene mejor mid-control' },
      { map: 'Split', score: 10, notes: 'Reina absoluta: satchel para Heaven/Screens control' },
      { map: 'Sunset', score: 8, notes: 'Satchel + nade para mapa compacto' },
      { map: 'Abyss', score: 7, notes: 'Satchel para lanzar enemigos al vacío' },
      { map: 'Corrode', score: 8, notes: 'Excelente en chokes cerrados con satchel' },
    ],
    bestWith: ['Breach', 'Brimstone', 'Sova', 'Omen', 'Fade'],
    strongAgainst: ['Sage', 'Cypher', 'Killjoy'],
    weakAgainst: ['KAY/O', 'Sova', 'Skye'],
    directReplacements: ['Jett', 'Neon', 'Yoru', 'Waylay'],
    archetypes: ['aggressive-tempo', 'double-duelist'],
    description: 'Duelista explosiva con satchel para plays verticales y nade para area-denial.',
    playstyle: 'Espacio caótico: satchel para entries verticales, nade para limpiar corners, ult para multi-kill.',
    proPickRate: 16.8,
    proWinRate: 50.1,
  },
  {
    name: 'Phoenix',
    role: 'Duelista',
    utility: ['entry', 'flash', 'heal', 'wall'],
    primaryUtility: 'entry',
    difficulty: 2,
    mapRatings: [
      { map: 'Ascent', score: 5, notes: 'Inferior a Jett/Raze para mid-control' },
      { map: 'Bind', score: 6, notes: 'Flash + wall para executes por dos frentes' },
      { map: 'Breeze', score: 4, notes: 'Líneas largas no favorecen su kit' },
      { map: 'Fracture', score: 5, notes: 'Raze/Neon más efectivos en pincer' },
      { map: 'Haven', score: 6, notes: 'Flash + wall para control de 3-sites' },
      { map: 'Icebox', score: 5, notes: 'Falta movilidad vertical necesaria en mapa' },
      { map: 'Lotus', score: 5, notes: 'Aceptable pero Raze tiene mejor explosividad' },
      { map: 'Pearl', score: 5, notes: 'Self-sufficient pero inferior a duelistas meta' },
      { map: 'Split', score: 6, notes: 'Flash + wall para chokes cerrados' },
      { map: 'Sunset', score: 6, notes: 'Aceptable en mapa compacto' },
      { map: 'Abyss', score: 5, notes: 'Flash + wall para control de platforms' },
      { map: 'Corrode', score: 5, notes: 'Aceptable pero hay mejores opciones' },
    ],
    bestWith: ['Omen', 'Breach', 'Sova', 'Brimstone'],
    strongAgainst: ['Sage', 'Deadlock'],
    weakAgainst: ['KAY/O', 'Sova', 'Breach'],
    directReplacements: ['Jett', 'Raze', 'Neon', 'Waylay'],
    archetypes: ['aggressive-tempo'],
    description: 'Duelista autocontenido con flash, wall de fuego y auto-heal.',
    playstyle: 'Self-sufficient: usar flash para entry, wall para cubrir, heal para mantenerse en ronda.',
    proPickRate: 2.5,
    proWinRate: 49.0,
  },
  {
    name: 'Reyna',
    role: 'Duelista',
    utility: ['entry', 'flash', 'heal'],
    primaryUtility: 'entry',
    difficulty: 2,
    mapRatings: [
      { map: 'Ascent', score: 4, notes: 'Falta utilidad de equipo para mid-control' },
      { map: 'Bind', score: 6, notes: 'Dismiss para escapes en executes' },
      { map: 'Breeze', score: 5, notes: 'Puede funcionar con Operator en líneas largas' },
      { map: 'Fracture', score: 4, notes: 'Falta utilidad para pincer coordinado' },
      { map: 'Haven', score: 5, notes: 'Leer para info pero no aporta macro' },
      { map: 'Icebox', score: 4, notes: 'Falta movilidad vertical' },
      { map: 'Lotus', score: 5, notes: 'Aceptable en duelos individuales' },
      { map: 'Pearl', score: 4, notes: 'Inferior a duelistas con utilidad de equipo' },
      { map: 'Split', score: 5, notes: 'Dismiss útil en chokes pero Raze mejor' },
      { map: 'Sunset', score: 5, notes: 'Puede funcionar pero no aporta utilidad de equipo' },
      { map: 'Abyss', score: 6, notes: 'Dismiss + Leer para control de vacío' },
      { map: 'Corrode', score: 4, notes: 'Falta utilidad necesaria en mapa' },
    ],
    bestWith: ['Omen', 'Sova', 'KAY/O', 'Fade', 'Chamber'],
    strongAgainst: ['Sage', 'Cypher'],
    weakAgainst: ['KAY/O', 'Breach', 'Skye'],
    directReplacements: ['Jett', 'Raze', 'Phoenix', 'Neon', 'Yoru'],
    archetypes: ['double-duelist'],
    description: 'Carry duelist que depende de kills para ser efectiva.',
    playstyle: 'Snowball: conseguir primer kill, dismiss para reposicionar, devour para heal y seguir.',
    proPickRate: 3.0,
    proWinRate: 49.5,
  },
  {
    name: 'Yoru',
    role: 'Duelista',
    utility: ['entry', 'flash', 'tp', 'lurk'],
    primaryUtility: 'entry',
    difficulty: 5,
    mapRatings: [
      { map: 'Ascent', score: 6, notes: 'TP + Fakeout para splits engañosos en mid' },
      { map: 'Bind', score: 7, notes: 'TP + teleporter para fakes avanzados' },
      { map: 'Breeze', score: 4, notes: 'Líneas largas castigan su kit' },
      { map: 'Fracture', score: 5, notes: 'TP para pincer pero Raze/Neon más directos' },
      { map: 'Haven', score: 8, notes: 'Excelente en 3-sites: TP + Fakeout para castigar rotaciones' },
      { map: 'Icebox', score: 5, notes: 'Falta movilidad vertical para el mapa' },
      { map: 'Lotus', score: 7, notes: 'TP + puertas para flanks creativos' },
      { map: 'Pearl', score: 6, notes: 'TP + Fakeout para engañar en mid' },
      { map: 'Split', score: 7, notes: 'TP para flanks + Flash para chokes' },
      { map: 'Sunset', score: 6, notes: 'TP para reposicionar en mapa compacto' },
      { map: 'Abyss', score: 5, notes: 'TP para reposicionar pero riesgo de caer al vacío' },
      { map: 'Corrode', score: 5, notes: 'TP para flanks pero hay mejores opciones' },
    ],
    bestWith: ['Omen', 'Sova', 'Fade', 'Iso', 'Cypher'],
    strongAgainst: ['Cypher', 'Sage', 'Deadlock'],
    weakAgainst: ['KAY/O', 'Sova', 'Skye'],
    directReplacements: ['Jett', 'Raze', 'Neon', 'Waylay'],
    archetypes: ['double-duelist', 'slow-control'],
    description: 'Flanker y trickster con teleport, flash y Fakeout para desinformación.',
    playstyle: 'Engaños: TP para flanks, Fakeout para vender presión, Gatecrash para reposicionar.',
    proPickRate: 4.0,
    proWinRate: 48.8,
  },
  {
    name: 'Iso',
    role: 'Duelista',
    utility: ['entry', 'shield', 'postplant'],
    primaryUtility: 'entry',
    difficulty: 3,
    mapRatings: [
      { map: 'Ascent', score: 5, notes: 'Contingency útil para mid pero Jett mejor' },
      { map: 'Bind', score: 6, notes: 'Shield para entries en executes' },
      { map: 'Breeze', score: 4, notes: 'Líneas largas no favorecen su kit cerrado' },
      { map: 'Fracture', score: 5, notes: 'Raze/Neon más efectivos en pincer' },
      { map: 'Haven', score: 7, notes: 'Shield + ult para duelos en 3-sites' },
      { map: 'Icebox', score: 4, notes: 'Falta movilidad vertical' },
      { map: 'Lotus', score: 6, notes: 'Shield para executar en 3-sites' },
      { map: 'Pearl', score: 5, notes: 'Inferior a duelistas con utilidad de equipo' },
      { map: 'Split', score: 6, notes: 'Shield para chokes pero Raze mejor' },
      { map: 'Sunset', score: 6, notes: 'Contingency + ult para mapa compacto' },
      { map: 'Abyss', score: 5, notes: 'Shield para control de platforms' },
      { map: 'Corrode', score: 5, notes: 'Aceptable pero hay mejores duelistas' },
    ],
    bestWith: ['Omen', 'Yoru', 'Sova', 'Tejo', 'Viper'],
    strongAgainst: ['Sage', 'Cypher'],
    weakAgainst: ['KAY/O', 'Breach', 'Skye'],
    directReplacements: ['Jett', 'Raze', 'Neon', 'Yoru'],
    archetypes: ['double-duelist'],
    description: 'Duelista adaptativo con escudo y ability para duelos controlados.',
    playstyle: 'Duelos medidos: usar Contingency para shield, Double Tap para trades, ult para ganar 1v1.',
    proPickRate: 3.5,
    proWinRate: 49.2,
  },
  {
    name: 'Neon',
    role: 'Duelista',
    utility: ['entry', 'mobility', 'concuss'],
    primaryUtility: 'entry',
    difficulty: 4,
    mapRatings: [
      { map: 'Ascent', score: 7, notes: 'Slide + Relay Bolt para mid-control rápido' },
      { map: 'Bind', score: 8, notes: 'Excelente en executes rápidos por dos frentes' },
      { map: 'Breeze', score: 5, notes: 'Líneas largas castigan su velocidad sin cobertura' },
      { map: 'Fracture', score: 8, notes: 'Top-tier: slide + ult para pincers rápidos' },
      { map: 'Haven', score: 7, notes: 'Velocidad para rotates entre 3-sites' },
      { map: 'Icebox', score: 6, notes: 'Slide para ángulos pero falta verticalidad real' },
      { map: 'Lotus', score: 7, notes: 'Slide + ult para executes en 3-sites' },
      { map: 'Pearl', score: 6, notes: 'Buena pero Jett tiene mejor mid-control' },
      { map: 'Split', score: 7, notes: 'Slide para chokes pero Raze tiene más explosividad' },
      { map: 'Sunset', score: 9, notes: 'Excelente en mapa compacto: slide para Elbow' },
      { map: 'Abyss', score: 7, notes: 'Slide para reposicionar rápido entre platforms' },
      { map: 'Corrode', score: 7, notes: 'Slide para chokes penetrables' },
    ],
    bestWith: ['Breach', 'Omen', 'Miks', 'Fade', 'Brimstone'],
    strongAgainst: ['Sage', 'Cypher', 'Deadlock'],
    weakAgainst: ['KAY/O', 'Tejo', 'Sova'],
    directReplacements: ['Jett', 'Raze', 'Waylay', 'Yoru'],
    archetypes: ['aggressive-tempo', 'double-duelist'],
    description: 'Duelista de tempo alto con movilidad y entrada rápida.',
    playstyle: 'Velocidad: slide para peeking agresivo, Relay Bolt para info, ult para site takes rápidos.',
    proPickRate: 7.5,
    proWinRate: 48.0,
  },
  {
    name: 'Waylay',
    role: 'Duelista',
    utility: ['entry', 'mobility', 'slow', 'concuss'],
    primaryUtility: 'entry',
    difficulty: 3,
    mapRatings: [
      { map: 'Ascent', score: 6, notes: 'Saturate + TP beacon para mid-control' },
      { map: 'Bind', score: 7, notes: 'TP beacon para reposicionar en executes' },
      { map: 'Breeze', score: 5, notes: 'Líneas largas no favorecen su kit' },
      { map: 'Fracture', score: 7, notes: 'TP + saturate para pincers' },
      { map: 'Haven', score: 6, notes: 'TP beacon para rotates entre 3-sites' },
      { map: 'Icebox', score: 5, notes: 'Falta verticalidad para mapa' },
      { map: 'Lotus', score: 7, notes: 'TP + saturate para puertas' },
      { map: 'Pearl', score: 6, notes: 'Aceptable pero hay duelistas más probados' },
      { map: 'Split', score: 7, notes: 'TP para chokes, saturate para limpiar' },
      { map: 'Sunset', score: 7, notes: 'TP + saturate para mapa compacto' },
      { map: 'Abyss', score: 6, notes: 'TP para reposicionar en platforms' },
      { map: 'Corrode', score: 6, notes: 'TP + saturate para chokes' },
    ],
    bestWith: ['Breach', 'Omen', 'Fade', 'Miks'],
    strongAgainst: ['Sage', 'Cypher'],
    weakAgainst: ['KAY/O', 'Sova', 'Skye'],
    directReplacements: ['Jett', 'Raze', 'Neon', 'Yoru'],
    archetypes: ['aggressive-tempo', 'double-duelist'],
    description: 'Duelista con teleport beacon y crowd-control para entradas coordinadas.',
    playstyle: 'Soporte de entrada: marcar con TP beacon, saturate para limpiar, reposicionar con teleport.',
    proPickRate: 1.7,
    proWinRate: 47.6,
  },
  {
    name: 'Sova',
    role: 'Iniciador',
    utility: ['recon', 'area-denial', 'postplant'],
    primaryUtility: 'recon',
    difficulty: 4,
    mapRatings: [
      { map: 'Ascent', score: 10, notes: 'Rey indiscutible: Recon Bolt + Shock Dart para mid-control' },
      { map: 'Bind', score: 6, notes: 'Útil pero Fade/Breach tienen más valor en chokes cerrados' },
      { map: 'Breeze', score: 9, notes: 'Excelente: Recon Bolt + Drone para líneas largas' },
      { map: 'Fracture', score: 7, notes: 'Útil pero Breach/Fade mejores para pincer' },
      { map: 'Haven', score: 9, notes: 'Recon para 3-sites, Drone para executes' },
      { map: 'Icebox', score: 9, notes: 'Top-tier: Recon + Drone para control vertical' },
      { map: 'Lotus', score: 7, notes: 'Bueno pero Fade tiene mejor info cercana' },
      { map: 'Pearl', score: 9, notes: 'Excelente: Recon para mid-control + Drone para executes' },
      { map: 'Split', score: 7, notes: 'Útil pero Breach/Fade mejores para chokes cerrados' },
      { map: 'Sunset', score: 7, notes: 'Bueno pero hay iniciadores más adaptados al mapa compacto' },
      { map: 'Abyss', score: 8, notes: 'Recon Bolt para control de platforms' },
      { map: 'Corrode', score: 8, notes: 'Recon + Shock Dart para líneas penetrables' },
    ],
    bestWith: ['Jett', 'Omen', 'Viper', 'Killjoy', 'Cypher'],
    strongAgainst: ['Killjoy', 'Cypher', 'Sage'],
    weakAgainst: ['KAY/O', 'Tejo', 'Skye'],
    directReplacements: ['Fade', 'Tejo'],
    archetypes: ['standard-balanced', 'double-initiator'],
    description: 'Iniciador recon clásico con dardos de información y daño.',
    playstyle: 'Info-driven: Recon Bolt al inicio, Drone para execute, Shock Dart para post-plant denials.',
    proPickRate: 15.0,
    proWinRate: 49.5,
  },
  {
    name: 'Skye',
    role: 'Iniciador',
    utility: ['flash', 'recon', 'heal', 'concuss'],
    primaryUtility: 'flash',
    difficulty: 3,
    mapRatings: [
      { map: 'Ascent', score: 8, notes: 'Flash + Dog para mid-control con healing' },
      { map: 'Bind', score: 8, notes: 'Flash + Dog ideales para executes por dos frentes' },
      { map: 'Breeze', score: 7, notes: 'Flash para líneas largas + heal sostenido' },
      { map: 'Fracture', score: 8, notes: 'Flash + Dog para pincers + Regrowth para equipo' },
      { map: 'Haven', score: 9, notes: 'Excelente en 3-sites: flash + heal + dog para rotates' },
      { map: 'Icebox', score: 7, notes: 'Flash + heal útil pero Sova mejor para vertical' },
      { map: 'Lotus', score: 8, notes: 'Dog + flash para 3-sites + heal sostenido' },
      { map: 'Pearl', score: 8, notes: 'Flash + heal para mid-control' },
      { map: 'Split', score: 8, notes: 'Flash + dog para chokes cerrados' },
      { map: 'Sunset', score: 8, notes: 'Flash + dog para mapa compacto' },
      { map: 'Abyss', score: 7, notes: 'Flash + dog para platforms' },
      { map: 'Corrode', score: 7, notes: 'Flash + heal para chokes' },
    ],
    bestWith: ['Jett', 'Raze', 'Omen', 'Viper', 'Phoenix'],
    strongAgainst: ['Killjoy', 'Cypher', 'Sage'],
    weakAgainst: ['KAY/O', 'Breach', 'Tejo'],
    directReplacements: ['KAY/O', 'Breach', 'Gekko', 'Tejo'],
    archetypes: ['standard-balanced', 'double-initiator'],
    description: 'Iniciadora con flash, healing y información con utilidad de equipo.',
    playstyle: 'Team-support: usar flash para entry, dog para info, Regrowth para sostener equipo.',
    proPickRate: 3.2,
    proWinRate: 49.0,
  },
  {
    name: 'Breach',
    role: 'Iniciador',
    utility: ['flash', 'concuss', 'stun', 'area-denial'],
    primaryUtility: 'flash',
    difficulty: 3,
    mapRatings: [
      { map: 'Ascent', score: 8, notes: 'Flash + stun para split executes + After Shock para corners' },
      { map: 'Bind', score: 8, notes: 'Excelente en executes por dos frentes con Raze' },
      { map: 'Breeze', score: 5, notes: 'Líneas largas castigan su kit de corto alcance' },
      { map: 'Fracture', score: 10, notes: 'Reina en pincer: stun + flash + ult para doble entrada' },
      { map: 'Haven', score: 7, notes: 'Flash + stun para executes en 3-sites' },
      { map: 'Icebox', score: 6, notes: 'Stun útil pero Sova mejor para vertical' },
      { map: 'Lotus', score: 7, notes: 'Flash + stun para executes en 3-sites' },
      { map: 'Pearl', score: 6, notes: 'Útil pero Skye/KAY/O tienen más rango' },
      { map: 'Split', score: 9, notes: 'Excelente: stun + flash + After Shock para chokes' },
      { map: 'Sunset', score: 7, notes: 'Flash + stun para mapa compacto' },
      { map: 'Abyss', score: 6, notes: 'Stun + ult para control de platforms' },
      { map: 'Corrode', score: 8, notes: 'Stun + flash para chokes penetrables' },
    ],
    bestWith: ['Raze', 'Neon', 'Brimstone', 'Omen', 'Fade'],
    strongAgainst: ['Sage', 'Cypher', 'Killjoy'],
    weakAgainst: ['KAY/O', 'Sova', 'Skye'],
    directReplacements: ['KAY/O', 'Skye', 'Gekko', 'Tejo'],
    archetypes: ['aggressive-tempo', 'double-initiator'],
    description: 'Iniciador de crowd-control con stuns, flashes y daño de área.',
    playstyle: 'Execute-enabler: stun + flash para entry, ult para team fight, After Shock para limpiar.',
    proPickRate: 6.5,
    proWinRate: 50.5,
  },
  {
    name: 'KAY/O',
    role: 'Iniciador',
    utility: ['flash', 'suppress', 'area-denial', 'crowd-control'],
    primaryUtility: 'suppress',
    difficulty: 3,
    mapRatings: [
      { map: 'Ascent', score: 8, notes: 'Knife + flash + suppress para mid-control' },
      { map: 'Bind', score: 7, notes: 'Suppress + flash para executes' },
      { map: 'Breeze', score: 7, notes: 'Suppress + knife para líneas largas' },
      { map: 'Fracture', score: 8, notes: 'Suppress para pincers + ult anti-utility' },
      { map: 'Haven', score: 8, notes: 'Knife + suppress para 3-sites' },
      { map: 'Icebox', score: 7, notes: 'Suppress + flash para control vertical' },
      { map: 'Lotus', score: 7, notes: 'Suppress + flash para 3-sites' },
      { map: 'Pearl', score: 8, notes: 'Suppress + knife para mid-control' },
      { map: 'Split', score: 8, notes: 'Suppress + flash para chokes cerrados' },
      { map: 'Sunset', score: 8, notes: 'Suppress + flash para mapa compacto' },
      { map: 'Abyss', score: 7, notes: 'Suppress + flash para platforms' },
      { map: 'Corrode', score: 7, notes: 'Suppress + flash para chokes' },
    ],
    bestWith: ['Jett', 'Raze', 'Omen', 'Sova', 'Phoenix'],
    strongAgainst: ['Viper', 'Killjoy', 'Cypher', 'Veto'],
    weakAgainst: ['Breach', 'Skye', 'Fade'],
    directReplacements: ['Skye', 'Breach', 'Gekko', 'Tejo'],
    archetypes: ['standard-balanced', 'double-initiator'],
    description: 'Iniciador con suppression, flashes y capacidad de combat revive.',
    playstyle: 'Anti-utility: Knife para suppress, flash para entry, ult para neutralizar utilidad enemiga.',
    proPickRate: 8.5,
    proWinRate: 49.0,
  },
  {
    name: 'Fade',
    role: 'Iniciador',
    utility: ['recon', 'flash', 'decay', 'crowd-control'],
    primaryUtility: 'recon',
    difficulty: 3,
    mapRatings: [
      { map: 'Ascent', score: 7, notes: 'Haunt + Prowler para mid-control cercano' },
      { map: 'Bind', score: 9, notes: 'Excelente: Haunt + Prowler para chokes cerrados' },
      { map: 'Breeze', score: 6, notes: 'Menor rango que Sova en líneas largas' },
      { map: 'Fracture', score: 8, notes: 'Haunt + Prowler para pincers cercanos' },
      { map: 'Haven', score: 7, notes: 'Haunt + Prowler para info cercana en 3-sites' },
      { map: 'Icebox', score: 6, notes: 'Sova mejor para control vertical' },
      { map: 'Lotus', score: 9, notes: 'Excelente: Haunt + Prowler para 3-sites + puertas' },
      { map: 'Pearl', score: 7, notes: 'Haunt para mid + Prowler para executes' },
      { map: 'Split', score: 8, notes: 'Haunt + Prowler para chokes cerrados' },
      { map: 'Sunset', score: 7, notes: 'Haunt + Prowler para mapa compacto' },
      { map: 'Abyss', score: 7, notes: 'Haunt + Prowler para platforms cerradas' },
      { map: 'Corrode', score: 7, notes: 'Haunt + Prowler para chokes' },
    ],
    bestWith: ['Raze', 'Omen', 'Neon', 'Viper', 'Jett'],
    strongAgainst: ['Killjoy', 'Cypher', 'Sage'],
    weakAgainst: ['KAY/O', 'Sova', 'Skye'],
    directReplacements: ['Sova', 'Tejo'],
    archetypes: ['standard-balanced', 'double-initiator'],
    description: 'Iniciadora recon cercano con crowd-control y decay.',
    playstyle: 'Info cercana: Haunt para reveal, Prowler para limpiar corners, Nightfall para retakes.',
    proPickRate: 7.0,
    proWinRate: 49.8,
  },
  {
    name: 'Gekko',
    role: 'Iniciador',
    utility: ['flash', 'recon', 'area-denial', 'postplant'],
    primaryUtility: 'flash',
    difficulty: 4,
    mapRatings: [
      { map: 'Ascent', score: 6, notes: 'Wingman + Dizzy para mid pero Sova mejor' },
      { map: 'Bind', score: 7, notes: 'Wingman plant/defuse + Dizzy para chokes' },
      { map: 'Breeze', score: 5, notes: 'Líneas largas castigan sus pets' },
      { map: 'Fracture', score: 7, notes: 'Wingman + Dizzy para pincers' },
      { map: 'Haven', score: 7, notes: 'Wingman para plantas seguras en 3-sites' },
      { map: 'Icebox', score: 5, notes: 'Falta verticalidad para pets' },
      { map: 'Lotus', score: 7, notes: 'Wingman + Dizzy para 3-sites' },
      { map: 'Pearl', score: 6, notes: 'Wingman útil pero Sova tiene mejor info' },
      { map: 'Split', score: 7, notes: 'Wingman + Dizzy para chokes' },
      { map: 'Sunset', score: 8, notes: 'Wingman + Dizzy ideales para mapa compacto' },
      { map: 'Abyss', score: 6, notes: 'Wingman plant/defuse útil en platforms' },
      { map: 'Corrode', score: 6, notes: 'Wingman + Dizzy para chokes' },
    ],
    bestWith: ['Omen', 'Raze', 'Neon', 'Viper', 'Jett'],
    strongAgainst: ['Sage', 'Cypher'],
    weakAgainst: ['KAY/O', 'Sova', 'Breach'],
    directReplacements: ['Skye', 'KAY/O', 'Breach', 'Tejo'],
    archetypes: ['standard-balanced', 'double-initiator'],
    description: 'Iniciador multi-utility con Wingman, Dizzy y Mosh para executes.',
    playstyle: 'Multi-tarea: Wingman para plant/defuse, Dizzy para flash, Mosh para area-denial.',
    proPickRate: 2.8,
    proWinRate: 48.5,
  },
  {
    name: 'Tejo',
    role: 'Iniciador',
    utility: ['recon', 'area-denial', 'suppress', 'crowd-control'],
    primaryUtility: 'recon',
    difficulty: 3,
    mapRatings: [
      { map: 'Ascent', score: 6, notes: 'Missiles para mid-control pero Sova tiene mejor info' },
      { map: 'Bind', score: 6, notes: 'Drone + missiles para executes' },
      { map: 'Breeze', score: 7, notes: 'Missiles + Drone para líneas largas' },
      { map: 'Fracture', score: 6, notes: 'Missiles para pincer pero Breach tiene mejor CC' },
      { map: 'Haven', score: 7, notes: 'Drone + missiles para 3-sites' },
      { map: 'Icebox', score: 6, notes: 'Missiles para control vertical' },
      { map: 'Lotus', score: 7, notes: 'Drone + missiles para 3-sites' },
      { map: 'Pearl', score: 6, notes: 'Útil pero Sova/KAY/O tienen más rango' },
      { map: 'Split', score: 6, notes: 'Missiles para chokes pero Breach mejor' },
      { map: 'Sunset', score: 7, notes: 'Drone + missiles para mapa compacto' },
      { map: 'Abyss', score: 8, notes: 'Excelente: missiles + suppress para control de vacío' },
      { map: 'Corrode', score: 7, notes: 'Missiles para chokes penetrables' },
    ],
    bestWith: ['Omen', 'Brimstone', 'Viper', 'Jett', 'Neon'],
    strongAgainst: ['Killjoy', 'Cypher', 'Sage'],
    weakAgainst: ['KAY/O', 'Sova', 'Breach'],
    directReplacements: ['Sova', 'Fade', 'Breach'],
    archetypes: ['standard-balanced', 'double-initiator'],
    description: 'Iniciador con área de daño y suppression para executes controlados.',
    playstyle: 'Presión: Drone para info, missiles para limpiar, suppress para negar utilidad defensiva.',
    proPickRate: 1.9,
    proWinRate: 48.5,
  },
  {
    name: 'Sage',
    role: 'Centinela',
    utility: ['heal', 'slow', 'wall', 'revive'],
    primaryUtility: 'heal',
    difficulty: 2,
    mapRatings: [
      { map: 'Ascent', score: 6, notes: 'Wall + Slow para retakes pero Killjoy mejor para anchor' },
      { map: 'Bind', score: 5, notes: 'Cypher/Killjoy tienen mejor info pasiva' },
      { map: 'Breeze', score: 5, notes: 'Wall útil pero Cypher mejor para flanks largos' },
      { map: 'Fracture', score: 6, notes: 'Heal + Rez para pincers pero Killjoy mejor anchor' },
      { map: 'Haven', score: 6, notes: 'Wall + Slow para 3-sites pero Cypher mejor info' },
      { map: 'Icebox', score: 7, notes: 'Wall para bloqueo vertical + Rez valiosa' },
      { map: 'Lotus', score: 5, notes: 'Killjoy/Cypher tienen mejor control pasivo' },
      { map: 'Pearl', score: 6, notes: 'Heal + Rez para sostén en mid-control' },
      { map: 'Split', score: 6, notes: 'Wall para chokes pero Killjoy mejor anchor' },
      { map: 'Sunset', score: 5, notes: 'Cypher/Killjoy tienen mejor utilidad pasiva' },
      { map: 'Abyss', score: 6, notes: 'Wall para controlar platforms' },
      { map: 'Corrode', score: 7, notes: 'Wall para bloquear líneas penetrables' },
    ],
    bestWith: ['All'],
    strongAgainst: ['Raze', 'Jett'],
    weakAgainst: ['Breach', 'KAY/O', 'Tejo'],
    directReplacements: ['Cypher', 'Killjoy', 'Chamber', 'Deadlock', 'Vyse', 'Veto'],
    archetypes: ['standard-balanced', 'slow-control'],
    description: 'Centinela support con healing, wall y resurrección.',
    playstyle: 'Support: heal sostenido, wall para bloquear rutas, Slow Orb para delay, Rez para clutch.',
    proPickRate: 4.5,
    proWinRate: 50.5,
  },
  {
    name: 'Cypher',
    role: 'Centinela',
    utility: ['trap', 'recon', 'slow'],
    primaryUtility: 'trap',
    difficulty: 3,
    mapRatings: [
      { map: 'Ascent', score: 9, notes: 'Excelente: Trapwire + Camera para mid-control + flank' },
      { map: 'Bind', score: 8, notes: 'Trapwire + Cam para executes por dos frentes' },
      { map: 'Breeze', score: 9, notes: 'Top-tier: Trapwire + Camera para flanks largos' },
      { map: 'Fracture', score: 8, notes: 'Trapwire + Camera para pincers + info pasiva' },
      { map: 'Haven', score: 10, notes: 'Rey en 3-sites: Trapwire cubre todo el mapa' },
      { map: 'Icebox', score: 8, notes: 'Trapwire + Camera para control vertical' },
      { map: 'Lotus', score: 8, notes: 'Trapwire + Camera para 3-sites + puertas' },
      { map: 'Pearl', score: 9, notes: 'Excelente: Trapwire + Camera para mid-control' },
      { map: 'Split', score: 9, notes: 'Trapwire + Camera para chokes + alturas' },
      { map: 'Sunset', score: 9, notes: 'Trapwire + Camera para mapa compacto' },
      { map: 'Abyss', score: 8, notes: 'Trapwire para controlar platforms' },
      { map: 'Corrode', score: 8, notes: 'Trapwire + Camera para chokes' },
    ],
    bestWith: ['Omen', 'Sova', 'Viper', 'Brimstone', 'Killjoy'],
    strongAgainst: ['Raze', 'Jett', 'Neon'],
    weakAgainst: ['Breach', 'Tejo', 'KAY/O'],
    directReplacements: ['Killjoy', 'Chamber', 'Sage', 'Deadlock', 'Vyse', 'Veto'],
    archetypes: ['standard-balanced', 'slow-control'],
    description: 'Centinela de información con trampas, cámara y ultimate de revelado.',
    playstyle: 'Info pasiva: Trapwire para detectar rotaciones, Cam para info, ult para retake.',
    proPickRate: 3.1,
    proWinRate: 49.4,
  },
  {
    name: 'Killjoy',
    role: 'Centinela',
    utility: ['trap', 'recon', 'slow', 'postplant'],
    primaryUtility: 'trap',
    difficulty: 3,
    mapRatings: [
      { map: 'Ascent', score: 9, notes: 'Excelente: Turret + Alarmbot + Nanoswarm para anchor A/B' },
      { map: 'Bind', score: 8, notes: 'Turret + Nanoswarm para executes por dos frentes' },
      { map: 'Breeze', score: 7, notes: 'Turret + Alarmbot para flanks largos' },
      { map: 'Fracture', score: 9, notes: 'Excelente: Turret + Lockdown para pincer defense' },
      { map: 'Haven', score: 8, notes: 'Turret + Nanoswarm para 3-sites' },
      { map: 'Icebox', score: 9, notes: 'Turret + Nanoswarm para anchor vertical' },
      { map: 'Lotus', score: 8, notes: 'Turret + Lockdown para 3-sites + puertas' },
      { map: 'Pearl', score: 8, notes: 'Turret + Nanoswarm para mid-control' },
      { map: 'Split', score: 8, notes: 'Turret + Nanoswarm para chokes' },
      { map: 'Sunset', score: 8, notes: 'Turret + Nanoswarm para mapa compacto' },
      { map: 'Abyss', score: 7, notes: 'Turret + Nanoswarm para control de platforms' },
      { map: 'Corrode', score: 8, notes: 'Turret + Lockdown para chokes' },
    ],
    bestWith: ['Omen', 'Viper', 'Sova', 'Brimstone', 'Raze'],
    strongAgainst: ['Raze', 'Jett', 'Neon', 'Phoenix'],
    weakAgainst: ['Tejo', 'Breach', 'KAY/O'],
    directReplacements: ['Cypher', 'Chamber', 'Sage', 'Deadlock', 'Vyse', 'Veto'],
    archetypes: ['standard-balanced', 'slow-control'],
    description: 'Centinela defensiva con turret, alarmbot y lockdown para retakes.',
    playstyle: 'Anchor: colocar Turret + Alarmbot + Nanoswarm para hold site, Lockdown para retake.',
    proPickRate: 12.0,
    proWinRate: 49.0,
  },
  {
    name: 'Chamber',
    role: 'Centinela',
    utility: ['trap', 'tp', 'lurk'],
    primaryUtility: 'tp',
    difficulty: 4,
    mapRatings: [
      { map: 'Ascent', score: 8, notes: 'TP + Headhunter para mid-control con Operator' },
      { map: 'Bind', score: 7, notes: 'TP + Trademark para executes por teleporter' },
      { map: 'Breeze', score: 8, notes: 'TP + Operator para líneas largas' },
      { map: 'Fracture', score: 6, notes: 'Killjoy/Cypher tienen mejor utilidad pasiva' },
      { map: 'Haven', score: 8, notes: 'TP + Headhunter para 3-sites con rotates rápidos' },
      { map: 'Icebox', score: 8, notes: 'TP + Operator para control vertical' },
      { map: 'Lotus', score: 7, notes: 'TP + Trademark para 3-sites + puertas' },
      { map: 'Pearl', score: 8, notes: 'TP + Operator para mid-control' },
      { map: 'Split', score: 6, notes: 'Cypher/Killjoy tienen mejor info pasiva' },
      { map: 'Sunset', score: 7, notes: 'TP + Headhunter para mapa compacto' },
      { map: 'Abyss', score: 9, notes: 'Excelente: TP + Operator para vacío control' },
      { map: 'Corrode', score: 7, notes: 'TP + Headhunter para chokes' },
    ],
    bestWith: ['Sova', 'Omen', 'Viper', 'Fade', 'Jett'],
    strongAgainst: ['Jett', 'Raze', 'Phoenix'],
    weakAgainst: ['Breach', 'KAY/O', 'Tejo'],
    directReplacements: ['Cypher', 'Killjoy', 'Sage', 'Deadlock', 'Vyse', 'Veto'],
    archetypes: ['standard-balanced', 'aggressive-tempo'],
    description: 'Centinela híbrido con teleport, Headhunter y ultimate de Operator.',
    playstyle: 'Agresivo-defensivo: Rendezvous para reposicionar, Trademark para slow, Headhunter/ult para kills.',
    proPickRate: 8.0,
    proWinRate: 48.5,
  },
  {
    name: 'Deadlock',
    role: 'Centinela',
    utility: ['trap', 'slow', 'concuss', 'wall'],
    primaryUtility: 'trap',
    difficulty: 3,
    mapRatings: [
      { map: 'Ascent', score: 6, notes: 'GravNet + Sensor para mid pero Killjoy/Cypher mejores' },
      { map: 'Bind', score: 5, notes: 'Trampas para executes pero menos rango que Killjoy' },
      { map: 'Breeze', score: 6, notes: 'GravNet + Sensor para flanks largos' },
      { map: 'Fracture', score: 6, notes: 'GravNet para pincers pero Killjoy mejor' },
      { map: 'Haven', score: 6, notes: 'Sensor + GravNet para 3-sites' },
      { map: 'Icebox', score: 7, notes: 'GravNet + Sensor para control vertical' },
      { map: 'Lotus', score: 6, notes: 'GravNet + Sensor para 3-sites' },
      { map: 'Pearl', score: 5, notes: 'Killjoy/Cypher tienen mejor info pasiva' },
      { map: 'Split', score: 7, notes: 'GravNet + Barrier Mesh para chokes' },
      { map: 'Sunset', score: 6, notes: 'GravNet + Sensor para mapa compacto' },
      { map: 'Abyss', score: 6, notes: 'GravNet para enviar al vacío' },
      { map: 'Corrode', score: 6, notes: 'GravNet + Sensor para chokes' },
    ],
    bestWith: ['Raze', 'Breach', 'Omen', 'Viper'],
    strongAgainst: ['Jett', 'Neon', 'Raze'],
    weakAgainst: ['Breach', 'KAY/O', 'Tejo'],
    directReplacements: ['Cypher', 'Killjoy', 'Chamber', 'Sage', 'Vyse', 'Veto'],
    archetypes: ['slow-control'],
    description: 'Centinela de denial de área con gravnet, sensor y barrier mesh.',
    playstyle: 'Denial: GravNet para atrapar, Sensor para info, Barrier Mesh para bloquear rotaciones.',
    proPickRate: 1.5,
    proWinRate: 49.0,
  },
  {
    name: 'Vyse',
    role: 'Centinela',
    utility: ['trap', 'flash', 'slow', 'area-denial'],
    primaryUtility: 'trap',
    difficulty: 4,
    mapRatings: [
      { map: 'Ascent', score: 6, notes: 'Arc Rose + Shear para mid pero Killjoy/Cypher probados' },
      { map: 'Bind', score: 6, notes: 'Arc Rose + Ambush para executes' },
      { map: 'Breeze', score: 5, notes: 'Falta rango para flanks largos' },
      { map: 'Fracture', score: 6, notes: 'Arc Rose + Shear para pincers' },
      { map: 'Haven', score: 6, notes: 'Arc Rose + Shear para 3-sites' },
      { map: 'Icebox', score: 5, notes: 'Falta verticalidad en utilidad' },
      { map: 'Lotus', score: 7, notes: 'Arc Rose + Shear para 3-sites + puertas' },
      { map: 'Pearl', score: 5, notes: 'Inferior a centinelas probados' },
      { map: 'Split', score: 6, notes: 'Arc Rose + Shear para chokes' },
      { map: 'Sunset', score: 6, notes: 'Arc Rose + Shear para mapa compacto' },
      { map: 'Abyss', score: 6, notes: 'Arc Rose para control de platforms' },
      { map: 'Corrode', score: 6, notes: 'Arc Rose + Shear para chokes' },
    ],
    bestWith: ['Breach', 'Raze', 'Omen', 'Viper'],
    strongAgainst: ['Jett', 'Neon', 'Raze'],
    weakAgainst: ['Breach', 'KAY/O', 'Sova'],
    directReplacements: ['Cypher', 'Killjoy', 'Chamber', 'Sage', 'Deadlock', 'Veto'],
    archetypes: ['slow-control', 'standard-balanced'],
    description: 'Centinela de control de área con stall, flash y shear para bloqueo.',
    playstyle: 'Stall: Arc Rose para negar área, Shear para bloquear, Ambush para kills sorpresa.',
    proPickRate: 0.9,
    proWinRate: 49.3,
  },
  {
    name: 'Veto',
    role: 'Centinela',
    utility: ['trap', 'recon', 'postplant'],
    primaryUtility: 'trap',
    difficulty: 4,
    mapRatings: [
      { map: 'Ascent', score: 6, notes: 'Outpost + Abyss para mid pero falta data pro' },
      { map: 'Bind', score: 5, notes: 'Outpost para executes pero Cypher/Killjoy probados' },
      { map: 'Breeze', score: 6, notes: 'Outpost para flanks largos' },
      { map: 'Fracture', score: 6, notes: 'Outpost + Abyss para pincers' },
      { map: 'Haven', score: 6, notes: 'Outpost + Abyss para 3-sites' },
      { map: 'Icebox', score: 5, notes: 'Falta verticalidad en utilidad' },
      { map: 'Lotus', score: 6, notes: 'Outpost + Abyss para 3-sites' },
      { map: 'Pearl', score: 5, notes: 'Inferior a centinelas probados' },
      { map: 'Split', score: 6, notes: 'Outpost + Abyss para chokes' },
      { map: 'Sunset', score: 6, notes: 'Outpost + Abyss para mapa compacto' },
      { map: 'Abyss', score: 5, notes: 'Nuevo agente, data limitada' },
      { map: 'Corrode', score: 5, notes: 'Nuevo agente, data limitada' },
    ],
    bestWith: ['Omen', 'Breach', 'Raze', 'Viper'],
    strongAgainst: ['Jett', 'Neon', 'Raze'],
    weakAgainst: ['KAY/O', 'Breach', 'Sova'],
    directReplacements: ['Cypher', 'Killjoy', 'Chamber', 'Sage', 'Deadlock', 'Vyse'],
    archetypes: ['slow-control', 'standard-balanced'],
    description: 'Centinela informativo con Outpost, Abyss y utilidad de post-plant.',
    playstyle: 'Info táctil: Outpost para multi-info, Abyss para picks tardíos, Contingency para post-plant.',
    proPickRate: 0.5,
    proWinRate: 48.2,
  },
];

export const getFullAgentProfile = (name: string): FullAgentProfile | undefined => {
  return ALL_AGENTS.find(a => a.name.toLowerCase() === name.toLowerCase());
};

export const getMapRatings = (name: string, map: ActiveMapName): number => {
  const profile = getFullAgentProfile(name);
  if (!profile) return 5;
  const rating = profile.mapRatings.find(r => r.map === map);
  return rating?.score || 5;
};

export const getAgentSynergies = (name: string): string[] => {
  const profile = getFullAgentProfile(name);
  return profile?.bestWith || [];
};

export const getAgentRole = (name: string): 'Duelista' | 'Controlador' | 'Iniciador' | 'Centinela' | undefined => {
  const profile = getFullAgentProfile(name);
  return profile?.role;
};

export const getMultiMapScore = (agentName: string): number => {
  const profile = getFullAgentProfile(agentName);
  if (!profile) return 50;
  const totalScore = profile.mapRatings.reduce((sum, r) => sum + r.score, 0);
  return (totalScore / profile.mapRatings.length) * 10;
};

export const getBestMaps = (agentName: string): { map: ActiveMapName; score: number }[] => {
  const profile = getFullAgentProfile(agentName);
  if (!profile) return [];
  return profile.mapRatings
    .filter(r => r.score >= 7)
    .map(r => ({ map: r.map, score: r.score }))
    .sort((a, b) => b.score - a.score);
};

export const getWeakMaps = (agentName: string): { map: ActiveMapName; score: number }[] => {
  const profile = getFullAgentProfile(agentName);
  if (!profile) return [];
  return profile.mapRatings
    .filter(r => r.score <= 5)
    .map(r => ({ map: r.map, score: r.score }))
    .sort((a, b) => a.score - b.score);
};

export const getDirectReplacement = (agentName: string): string[] => {
  const profile = getFullAgentProfile(agentName);
  return profile?.directReplacements || [];
};

export const isDirectReplacement = (agentName: string, replacement: string): boolean => {
  const profile = getFullAgentProfile(agentName);
  return profile?.directReplacements.some(
    r => r.toLowerCase() === replacement.toLowerCase()
  ) || false;
};